---
title: "In-class Exercise 1: First Date with Geospatial Data Analytics"
date: "18 November 2023"
date-modified: "last-modified"
---

## Getting Started

the code chunk below load the following packages:

-   tmap: thematic mapping.

-   sf: for geospatial data handling.

-   tidyverse: for non-spatial data handling.

```{r}
pacman::p_load(tmap, sf, tidyverse)
```

## Importing Data

### Importing OD data

import data of *Passenger Volume by Origin Destination Bus Stop* dataset from LTA Data Mall utilising read_csv() of **readr** package.

```{r}
odbus = read_csv("data/aspatial/origin_destination_bus_202308.csv")
```

changing origin and destination pt code from CHR to Factor

```{r}
odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE)
odbus$DESTINATION_PT_CODE <- as.factor(odbus$DESTINATION_PT_CODE)
```

picking data from 7 to 9 and in weekday

```{r}
origtrip_7_9 <- odbus %>%
  filter(DAY_TYPE == "WEEKDAY") %>%
  filter(TIME_PER_HOUR >= 7 &
           TIME_PER_HOUR <= 9) %>%
  group_by(ORIGIN_PT_CODE) %>%
  summarise(TRIPS = sum(TOTAL_TRIPS))
```

### Importing geospatial data

#### bus stop

```{r}
busstop <- st_read(dsn = "data/geospatial",
                   layer = "BusStop") %>%
  st_transform(crs = 3414)
```

```{r}
mpsz <- st_read(dsn = "data/geospatial",
                   layer = "MPSZ-2019") %>%
  st_transform(crs = 3414)
mpsz
```
